package verify

import (
	"bytes"
	"fmt"
	"go/format"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/robertguss/go-foundry-cli/internal/diagnostic"
)

// GoFmtFailure names one staged .go file that is not go/format-clean.
type GoFmtFailure struct {
	Rel    string
	Detail string
}

// CheckGoFmt walks stageRoot and asserts every regular .go file is
// go/format-idempotent (Section 35.1 / REQ-126 / REQ-150). In-process only —
// not a gofmt subprocess.
//
// Skips vendor/, testdata/ is NOT skipped (generated tests must also be clean).
// Skips .git. Non-Go files are ignored.
func CheckGoFmt(stageRoot string) ([]GoFmtFailure, error) {
	if stageRoot == "" {
		return nil, diagnostic.Newf(
			diagnostic.IDVerifyFailed,
			diagnostic.StepLocation(CheckGofmt),
			"empty stage root for gofmt conformance",
		)
	}
	root := filepath.Clean(stageRoot)
	var fails []GoFmtFailure
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(root, path)
		if err != nil {
			return err
		}
		relSlash := filepath.ToSlash(rel)
		if relSlash == ".git" || strings.HasPrefix(relSlash, ".git/") {
			if d.IsDir() {
				return fs.SkipDir
			}
			return nil
		}
		if d.IsDir() {
			// Skip vendored trees if present (not generated by Foundry, but
			// defense-in-depth for hostile stages).
			if d.Name() == "vendor" {
				return fs.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(relSlash, ".go") {
			return nil
		}
		info, err := d.Info()
		if err != nil {
			return err
		}
		if !info.Mode().IsRegular() {
			return nil
		}
		src, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		formatted, ferr := format.Source(src)
		if ferr != nil {
			fails = append(fails, GoFmtFailure{
				Rel:    relSlash,
				Detail: fmt.Sprintf("go/format error: %v", ferr),
			})
			return nil
		}
		if !bytes.Equal(src, formatted) {
			fails = append(fails, GoFmtFailure{
				Rel:    relSlash,
				Detail: "not go/format-idempotent (bytes differ after format.Source)",
			})
		}
		return nil
	})
	if err != nil {
		return fails, diagnostic.Wrapf(
			diagnostic.IDVerifyFailed,
			diagnostic.StepLocation(CheckGofmt),
			err,
			"gofmt walk failed: %v", err,
		)
	}
	if len(fails) > 0 {
		paths := make([]string, 0, len(fails))
		for _, f := range fails {
			paths = append(paths, f.Rel)
		}
		return fails, diagnostic.Newf(
			diagnostic.IDVerifyFailed,
			diagnostic.StepLocation(CheckGofmt),
			"gofmt conformance failed for %d file(s): %s",
			len(fails), strings.Join(paths, ", "),
		).WithRemediation(
			"Ensure every staged .go file is go/format-clean. " +
				"Renderer must emit format-idempotent Go source (REQ-126). " +
				"Inspect the preserved stage paths named in the error.",
		)
	}
	return nil, nil
}
