package render_test

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
	"testing"

	"github.com/robertguss/go-foundry-cli/internal/diagnostic"
	"github.com/robertguss/go-foundry-cli/internal/render"
	"github.com/robertguss/go-foundry-cli/internal/testutil"
)

// minimalCLITemplateData is the frozen data bag for the minimal-cli shell
// fixtures (examples/minimal-cli.toml defaults).
func minimalCLITemplateData() render.TemplateData {
	return render.TemplateData{
		Name:                "minimal-cli",
		Binary:              "minimal-cli",
		Module:              "github.com/example/minimal-cli",
		Description:         "Minimal Foundry CLI example for validate, plan, and generate",
		Archetype:           "cli",
		Visibility:          "private",
		FoundryVersion:      "0.1.0",
		DistributionEnabled: false,
	}
}

func templateFixtureCatalog() mapCatalog {
	return mapCatalog{
		"core/files/README.md.tmpl": []byte(
			"# [[.Name]]\n\n[[.Description]]\n\nGenerated by Foundry. Edit freely after generation (DEC-002).\n",
		),
		"archetypes/cli/files/main.go.tmpl": []byte(
			"// Code generated by Foundry; DO NOT EDIT if regenerating.\n" +
				"// Package main is the process boundary for [[.Binary]].\n" +
				"package main\n\n" +
				"func main() {\n" +
				"\t// Stub: full CLI shell lands in archetype content beads.\n" +
				"}\n",
		),
		"archetypes/tui/files/main.go.tmpl": []byte(
			"// Code generated by Foundry; DO NOT EDIT if regenerating.\n" +
				"// Package main is the process boundary for [[.Binary]].\n" +
				"package main\n\n" +
				"func main() {\n" +
				"\t// Stub: full TUI shell lands in archetype content beads.\n" +
				"}\n",
		),
		"fixtures/simple.tmpl": []byte("Hello [[.Name]] ([[.Binary]])\n"),
		"fixtures/unknown_field.tmpl": []byte(
			"[[.DoesNotExist]]\n",
		),
		"fixtures/nested_define.tmpl": []byte(
			"[[define \"partial\"]]secret[[end]]\n[[template \"partial\"]]\n",
		),
		"fixtures/include_only.tmpl": []byte(
			"[[template \"missing\"]]\n",
		),
		"fixtures/forbidden_call.tmpl": []byte(
			"[[call .Name]]\n",
		),
		"fixtures/forbidden_exec.tmpl": []byte(
			"[[exec \"rm -rf /\"]]\n",
		),
		"fixtures/default_delims_literal.tmpl": []byte(
			"literal={{.Name}} action=[[.Name]]\n",
		),
		"fixtures/crlf.tmpl": []byte(
			"# [[.Name]]\r\nline2\r\n",
		),
		"fixtures/distribution.tmpl": []byte(
			"[[if .DistributionEnabled]]dist=yes[[else]]dist=no[[end]]\n",
		),
		"fixtures/bad_go.tmpl": []byte(
			"package main\nfunc main( [[.Name]] ) {\n",
		),
	}
}

// TestTemplateCLIMinimalShellGoldens locks golden renders for each catalog
// template fixture used by the CLI minimal shell (README + cmd main).
func TestTemplateCLIMinimalShellGoldens(t *testing.T) {
	log := testutil.New(t)
	log.Phase("arrange")
	cat := mustLoadCatalog(t)
	data := minimalCLITemplateData()
	jobs := []render.TemplateJob{
		{
			Path:   "README.md",
			Mode:   "0644",
			Source: "core/files/README.md.tmpl",
			Owner:  "core",
			Data:   data,
		},
		{
			Path:   "cmd/minimal-cli/main.go",
			Mode:   "0644",
			Source: "archetypes/cli/files/main.go.tmpl",
			Owner:  "archetype:cli",
			Data:   data,
		},
	}
	log.Inputs(map[string]string{
		"mechanism": "template",
		"files":     fmt.Sprintf("%d", len(jobs)),
		"name":      data.Name,
		"binary":    data.Binary,
	})
	log.Fixture("fixture", "minimal-cli")
	log.PhaseEnd("arrange", testutil.OutcomeOK)

	log.Phase("act")
	buf := render.NewMemoryWriter()
	inv, err := render.RenderTemplateAll(cat, jobs, buf)
	if err != nil {
		log.Fail("render_template_all", err.Error())
	}
	log.Step("inventory", testutil.OutcomeOK, fmt.Sprintf("n=%d paths=%v", inv.Len(), inv.Paths()))
	log.PhaseEnd("act", testutil.OutcomeOK)

	log.Phase("assert")
	log.Assert("entry_count", inv.Len() == 2, 2, inv.Len())

	// Sorted by path: README.md, cmd/minimal-cli/main.go
	cases := []struct {
		path   string
		source string
		golden string
		owner  string
		isGo   bool
	}{
		{
			path:   "README.md",
			source: "core/files/README.md.tmpl",
			golden: "minimal_cli_readme",
			owner:  "core",
		},
		{
			path:   "cmd/minimal-cli/main.go",
			source: "archetypes/cli/files/main.go.tmpl",
			golden: "minimal_cli_main_go",
			owner:  "archetype:cli",
			isGo:   true,
		},
	}
	for _, tc := range cases {
		e, ok := inv.EntryByPath(tc.path)
		log.Assert("found_"+tc.path, ok, true, ok)
		log.Assert("mech_"+tc.path, e.Mechanism == render.MechanismTemplate,
			render.MechanismTemplate, e.Mechanism)
		log.Assert("mode_"+tc.path, e.Mode == "0644", "0644", e.Mode)
		log.Assert("source_"+tc.path, e.Source == tc.source, tc.source, e.Source)
		log.Assert("owner_"+tc.path, e.Owner == tc.owner, tc.owner, e.Owner)

		src, rerr := cat.Read(tc.source)
		if rerr != nil {
			log.Fail("read_source_"+tc.path, rerr.Error())
		}
		srcDig := digestOf(src)
		log.Assert("source_digest_"+tc.path, e.SourceDigest == srcDig, srcDig, e.SourceDigest)

		out, cok := inv.Content(tc.path)
		log.Assert("content_present_"+tc.path, cok, true, cok)
		log.Assert("content_digest_"+tc.path, e.ContentDigest == digestOf(out),
			digestOf(out), e.ContentDigest)
		// Template output differs from source when substitution occurs.
		log.Assert("digest_differs_"+tc.path, e.SourceDigest != e.ContentDigest,
			true, e.SourceDigest != e.ContentDigest)

		// No CR in rendered output (LF-only).
		log.Assert("lf_only_"+tc.path, !bytes.Contains(out, []byte{'\r'}),
			true, !bytes.Contains(out, []byte{'\r'}))

		if tc.isGo {
			log.Assert("go_package_"+tc.path, bytes.Contains(out, []byte("package main")),
				true, bytes.Contains(out, []byte("package main")))
			log.Assert("go_binary_"+tc.path, bytes.Contains(out, []byte(data.Binary)),
				true, bytes.Contains(out, []byte(data.Binary)))
		} else {
			log.Assert("name_in_readme", bytes.Contains(out, []byte("# "+data.Name)),
				true, bytes.Contains(out, []byte("# "+data.Name)))
			log.Assert("desc_in_readme", bytes.Contains(out, []byte(data.Description)),
				true, bytes.Contains(out, []byte(data.Description)))
		}

		golden := testutil.GoldenPath(filepath.Join(packageDir(t), "testdata"), tc.golden)
		testutil.CompareGolden(t, golden, out)
		log.Step("file", testutil.OutcomeOK, fmt.Sprintf(
			"template_id=%s input_digest=%s output_digest=%s path=%s outcome=ok",
			e.Source, e.SourceDigest, e.ContentDigest, e.Path,
		))
		log.NotePath(e.Path)
		log.NoteID(string(e.ContentDigest))
	}
	log.PhaseEnd("assert", testutil.OutcomeOK)
}

// TestTemplateUnknownIdentifierFailClosed ensures missing fields yield
// render.failed (missingkey=error) with no partial best-effort output.
func TestTemplateUnknownIdentifierFailClosed(t *testing.T) {
	log := testutil.New(t)
	log.Phase("unknown_field")
	cat := templateFixtureCatalog()
	inv, err := render.RenderTemplate(cat, render.TemplateJob{
		Path:   "out.txt",
		Mode:   "0644",
		Source: "fixtures/unknown_field.tmpl",
		Data:   minimalCLITemplateData(),
	}, nil)
	log.Assert("nil_inventory", inv == nil, true, inv == nil)
	if err == nil {
		log.Fail("expected_error", "want render.failed for unknown identifier")
	}
	fe := asFoundry(t, err)
	log.Assert("id", fe.ID() == diagnostic.IDRenderFailed,
		diagnostic.IDRenderFailed, fe.ID())
	log.Step("unknown", testutil.OutcomeOK, fmt.Sprintf(
		"template_id=fixtures/unknown_field.tmpl error_id=%s outcome=fail",
		fe.ID(),
	))
	log.NoteID(string(fe.ID()))
	log.PhaseEnd("unknown_field", testutil.OutcomeOK)
}

// TestTemplateNoNestedPartials rejects define + template include.
func TestTemplateNoNestedPartials(t *testing.T) {
	log := testutil.New(t)
	log.Phase("no_partials")
	cat := templateFixtureCatalog()

	cases := []struct {
		name   string
		source string
		sub    string
	}{
		{name: "nested_define", source: "fixtures/nested_define.tmpl", sub: "define"},
		{name: "include", source: "fixtures/include_only.tmpl", sub: "include"},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			sub := testutil.New(t)
			sub.Phase("reject")
			sub.Inputs(map[string]string{"source": tc.source, "case": tc.name})
			inv, err := render.RenderTemplate(cat, render.TemplateJob{
				Path:   "out.txt",
				Mode:   "0644",
				Source: tc.source,
				Data:   minimalCLITemplateData(),
			}, nil)
			sub.Assert("nil_inventory", inv == nil, true, inv == nil)
			if err == nil {
				sub.Fail("expected_error", "want render.failed for "+tc.name)
			}
			fe := asFoundry(t, err)
			sub.Assert("id", fe.ID() == diagnostic.IDRenderFailed,
				diagnostic.IDRenderFailed, fe.ID())
			msg := fe.Error()
			sub.Assert("mentions_restriction",
				strings.Contains(msg, "not allowed") ||
					strings.Contains(msg, "complete-file") ||
					strings.Contains(msg, "partial") ||
					strings.Contains(msg, "include") ||
					strings.Contains(msg, "definition"),
				true, msg)
			sub.Step("reject", testutil.OutcomeOK, fmt.Sprintf(
				"template_id=%s error_id=%s outcome=refused",
				tc.source, fe.ID(),
			))
			sub.PhaseEnd("reject", testutil.OutcomeOK)
		})
	}
	log.PhaseEnd("no_partials", testutil.OutcomeOK)
}

// TestTemplateNoExternalExecution rejects exec/call-style actions and proves
// ordinary renders never shell out (pure buffer only).
func TestTemplateNoExternalExecution(t *testing.T) {
	log := testutil.New(t)
	log.Phase("no_exec")
	cat := templateFixtureCatalog()

	// Hostile function names fail closed.
	for _, src := range []string{
		"fixtures/forbidden_call.tmpl",
		"fixtures/forbidden_exec.tmpl",
	} {
		src := src
		t.Run(src, func(t *testing.T) {
			t.Parallel()
			sub := testutil.New(t)
			sub.Phase("reject")
			inv, err := render.RenderTemplate(cat, render.TemplateJob{
				Path:   "out.txt",
				Mode:   "0644",
				Source: src,
				Data:   minimalCLITemplateData(),
			}, nil)
			sub.Assert("nil_inventory", inv == nil, true, inv == nil)
			if err == nil {
				sub.Fail("expected_error", "want render.failed for hostile func")
			}
			fe := asFoundry(t, err)
			sub.Assert("id", fe.ID() == diagnostic.IDRenderFailed,
				diagnostic.IDRenderFailed, fe.ID())
			sub.Step("reject", testutil.OutcomeOK, fmt.Sprintf(
				"template_id=%s error_id=%s outcome=refused",
				src, fe.ID(),
			))
			sub.PhaseEnd("reject", testutil.OutcomeOK)
		})
	}

	// Safe render produces only substituted text — no side-effect channels.
	inv, err := render.RenderTemplate(cat, render.TemplateJob{
		Path:   "hello.txt",
		Mode:   "0644",
		Source: "fixtures/simple.tmpl",
		Data:   minimalCLITemplateData(),
	}, nil)
	if err != nil {
		log.Fail("safe_render", err.Error())
	}
	out, ok := inv.Content("hello.txt")
	log.Assert("present", ok, true, ok)
	want := "Hello minimal-cli (minimal-cli)\n"
	log.Assert("bytes", string(out) == want, want, string(out))
	log.Step("safe", testutil.OutcomeOK, fmt.Sprintf(
		"template_id=fixtures/simple.tmpl input_digest=%s output_digest=%s outcome=ok",
		inv.Entries()[0].SourceDigest, inv.Entries()[0].ContentDigest,
	))
	log.PhaseEnd("no_exec", testutil.OutcomeOK)
}

// TestTemplateApprovedDelimitersOnly proves default {{ }} delimiters are
// treated as literal text; only [[ ]] are actions.
func TestTemplateApprovedDelimitersOnly(t *testing.T) {
	log := testutil.New(t)
	log.Phase("delimiters")
	cat := templateFixtureCatalog()
	inv, err := render.RenderTemplate(cat, render.TemplateJob{
		Path:   "out.txt",
		Mode:   "0644",
		Source: "fixtures/default_delims_literal.tmpl",
		Data:   minimalCLITemplateData(),
	}, nil)
	if err != nil {
		log.Fail("render", err.Error())
	}
	out, _ := inv.Content("out.txt")
	want := "literal={{.Name}} action=minimal-cli\n"
	log.Assert("literal_default_delims", string(out) == want, want, string(out))
	log.Assert("constants", render.TemplateLeftDelim == "[[" && render.TemplateRightDelim == "]]",
		"[[ / ]]", render.TemplateLeftDelim+" / "+render.TemplateRightDelim)
	log.Step("delims", testutil.OutcomeOK, fmt.Sprintf(
		"template_id=fixtures/default_delims_literal.tmpl output_digest=%s outcome=ok",
		inv.Entries()[0].ContentDigest,
	))
	log.PhaseEnd("delimiters", testutil.OutcomeOK)
}

// TestTemplateJoinQuoteFunctions exercises the only admitted custom functions.
func TestTemplateJoinQuoteFunctions(t *testing.T) {
	log := testutil.New(t)
	log.Phase("join_quote")

	out, err := render.ExecuteTemplate("quote.tmpl",
		[]byte("q=[[quote .Name]]\n"),
		minimalCLITemplateData(), "out.txt")
	if err != nil {
		log.Fail("quote", err.Error())
	}
	log.Assert("quoted", string(out) == "q=\"minimal-cli\"\n",
		"q=\"minimal-cli\"\n", string(out))

	joined, err := render.ExecuteTemplate("join.tmpl",
		[]byte("j=[[join \", \" .Name .Binary .Archetype]]\n"),
		minimalCLITemplateData(), "out.txt")
	if err != nil {
		log.Fail("join", err.Error())
	}
	wantJoin := "j=minimal-cli, minimal-cli, cli\n"
	log.Assert("joined", string(joined) == wantJoin, wantJoin, string(joined))

	pathish, err := render.ExecuteTemplate("join-path.tmpl",
		[]byte("p=[[join \"/\" \"cmd\" .Binary \"main.go\"]]\n"),
		minimalCLITemplateData(), "out.txt")
	if err != nil {
		log.Fail("join_path", err.Error())
	}
	wantPath := "p=cmd/minimal-cli/main.go\n"
	log.Assert("join_path", string(pathish) == wantPath, wantPath, string(pathish))

	log.Step("join_quote", testutil.OutcomeOK, "quote=ok join=ok")
	log.PhaseEnd("join_quote", testutil.OutcomeOK)
}

// TestTemplateDeterminism ensures identical inputs produce equal inventories
// under repeated invocation (pair with go test -count=2).
func TestTemplateDeterminism(t *testing.T) {
	log := testutil.New(t)
	log.Phase("determinism")
	cat := mustLoadCatalog(t)
	data := minimalCLITemplateData()
	jobs := []render.TemplateJob{
		{Path: "README.md", Mode: "0644", Source: "core/files/README.md.tmpl", Owner: "core", Data: data},
		{Path: "cmd/minimal-cli/main.go", Mode: "0644", Source: "archetypes/cli/files/main.go.tmpl", Owner: "archetype:cli", Data: data},
	}

	a, err := render.RenderTemplateAll(cat, jobs, render.NewMemoryWriter())
	if err != nil {
		log.Fail("render_a", err.Error())
	}
	b, err := render.RenderTemplateAll(cat, jobs, render.NewMemoryWriter())
	if err != nil {
		log.Fail("render_b", err.Error())
	}
	log.Assert("equal", a.Equal(b), true, a.Equal(b))
	for i, e := range a.Entries() {
		log.Assert("path_"+e.Path, e.Path == b.Entries()[i].Path, e.Path, b.Entries()[i].Path)
		log.Assert("digest_"+e.Path, e.ContentDigest == b.Entries()[i].ContentDigest,
			e.ContentDigest, b.Entries()[i].ContentDigest)
		log.Step("file", testutil.OutcomeOK, fmt.Sprintf(
			"template_id=%s input_digest=%s output_digest=%s outcome=ok",
			e.Source, e.SourceDigest, e.ContentDigest,
		))
	}
	log.PhaseEnd("determinism", testutil.OutcomeOK)
}

// TestTemplateStepLogger records template id, input digest, output digest,
// and error id on failure paths.
func TestTemplateStepLogger(t *testing.T) {
	log := testutil.New(t)
	log.Phase("step_logger")
	cat := mustLoadCatalog(t)
	data := minimalCLITemplateData()
	src := "core/files/README.md.tmpl"

	inv, err := render.RenderTemplate(cat, render.TemplateJob{
		Path:   "README.md",
		Mode:   "0644",
		Source: src,
		Owner:  "core",
		Data:   data,
	}, nil)
	if err != nil {
		log.Fail("render", err.Error())
	}
	e := inv.Entries()[0]
	log.Step("template", testutil.OutcomeOK, fmt.Sprintf(
		"template_id=%s input_digest=%s output_digest=%s error_id= outcome=ok",
		e.Source, e.SourceDigest, e.ContentDigest,
	))
	log.Assert("template_id", e.Source == src, src, e.Source)
	log.Assert("input_digest_nonempty", e.SourceDigest != "", true, e.SourceDigest != "")
	log.Assert("output_digest_nonempty", e.ContentDigest != "", true, e.ContentDigest != "")
	log.NotePath(e.Path)
	log.NoteID(string(e.ContentDigest))

	// Failure path logs error id.
	_, err = render.RenderTemplate(templateFixtureCatalog(), render.TemplateJob{
		Path:   "out.txt",
		Mode:   "0644",
		Source: "fixtures/unknown_field.tmpl",
		Data:   data,
	}, nil)
	if err == nil {
		log.Fail("expected_error", "want render.failed")
	}
	fe := asFoundry(t, err)
	log.Step("template_fail", testutil.OutcomeOK, fmt.Sprintf(
		"template_id=fixtures/unknown_field.tmpl input_digest= output_digest= error_id=%s outcome=fail",
		fe.ID(),
	))
	log.Assert("error_id", fe.ID() == diagnostic.IDRenderFailed,
		diagnostic.IDRenderFailed, fe.ID())
	log.PhaseEnd("step_logger", testutil.OutcomeOK)
}

// TestTemplateLFNormalization converts CRLF sources to LF-only output.
func TestTemplateLFNormalization(t *testing.T) {
	log := testutil.New(t)
	log.Phase("lf")
	cat := templateFixtureCatalog()
	inv, err := render.RenderTemplate(cat, render.TemplateJob{
		Path:   "out.md",
		Mode:   "0644",
		Source: "fixtures/crlf.tmpl",
		Data:   minimalCLITemplateData(),
	}, nil)
	if err != nil {
		log.Fail("render", err.Error())
	}
	out, _ := inv.Content("out.md")
	log.Assert("no_cr", !bytes.Contains(out, []byte{'\r'}), true, !bytes.Contains(out, []byte{'\r'}))
	log.Assert("has_lf", bytes.Contains(out, []byte{'\n'}), true, bytes.Contains(out, []byte{'\n'}))
	log.Assert("content", string(out) == "# minimal-cli\nline2\n",
		"# minimal-cli\nline2\n", string(out))
	log.Step("lf", testutil.OutcomeOK, fmt.Sprintf(
		"template_id=fixtures/crlf.tmpl output_digest=%s outcome=ok",
		inv.Entries()[0].ContentDigest,
	))
	log.PhaseEnd("lf", testutil.OutcomeOK)
}

// TestTemplateDistributionEnabledFact toggles the frozen boolean fact.
func TestTemplateDistributionEnabledFact(t *testing.T) {
	log := testutil.New(t)
	log.Phase("distribution_fact")
	cat := templateFixtureCatalog()
	for _, enabled := range []bool{false, true} {
		enabled := enabled
		t.Run(fmt.Sprintf("enabled_%v", enabled), func(t *testing.T) {
			t.Parallel()
			sub := testutil.New(t)
			sub.Phase("render")
			data := minimalCLITemplateData()
			data.DistributionEnabled = enabled
			inv, err := render.RenderTemplate(cat, render.TemplateJob{
				Path:   "dist.txt",
				Mode:   "0644",
				Source: "fixtures/distribution.tmpl",
				Data:   data,
			}, nil)
			if err != nil {
				sub.Fail("render", err.Error())
			}
			out, _ := inv.Content("dist.txt")
			want := "dist=no\n"
			if enabled {
				want = "dist=yes\n"
			}
			sub.Assert("branch", string(out) == want, want, string(out))
			sub.Step("fact", testutil.OutcomeOK, fmt.Sprintf(
				"DistributionEnabled=%v output_digest=%s",
				enabled, inv.Entries()[0].ContentDigest,
			))
			sub.PhaseEnd("render", testutil.OutcomeOK)
		})
	}
	log.PhaseEnd("distribution_fact", testutil.OutcomeOK)
}

// TestTemplateBadGoSourceFailsFormat rejects unparseable Go after render.
func TestTemplateBadGoSourceFailsFormat(t *testing.T) {
	log := testutil.New(t)
	log.Phase("bad_go")
	cat := templateFixtureCatalog()
	inv, err := render.RenderTemplate(cat, render.TemplateJob{
		Path:   "cmd/x/main.go",
		Mode:   "0644",
		Source: "fixtures/bad_go.tmpl",
		Data:   minimalCLITemplateData(),
	}, nil)
	log.Assert("nil_inventory", inv == nil, true, inv == nil)
	if err == nil {
		log.Fail("expected_error", "want render.failed for bad Go")
	}
	fe := asFoundry(t, err)
	log.Assert("id", fe.ID() == diagnostic.IDRenderFailed,
		diagnostic.IDRenderFailed, fe.ID())
	log.Assert("mentions_format",
		strings.Contains(fe.Error(), "go/format") || strings.Contains(fe.Error(), "format"),
		true, fe.Error())
	log.Step("bad_go", testutil.OutcomeOK, fmt.Sprintf(
		"template_id=fixtures/bad_go.tmpl error_id=%s outcome=fail", fe.ID(),
	))
	log.PhaseEnd("bad_go", testutil.OutcomeOK)
}

// TestTemplateRefusePathEscape refuses .. and absolute paths.
func TestTemplateRefusePathEscape(t *testing.T) {
	log := testutil.New(t)
	log.Phase("escape")
	cat := templateFixtureCatalog()
	cases := []struct {
		name string
		job  render.TemplateJob
	}{
		{
			name: "dotdot_path",
			job:  render.TemplateJob{Path: "../escape", Mode: "0644", Source: "fixtures/simple.tmpl", Data: minimalCLITemplateData()},
		},
		{
			name: "absolute_path",
			job:  render.TemplateJob{Path: "/etc/passwd", Mode: "0644", Source: "fixtures/simple.tmpl", Data: minimalCLITemplateData()},
		},
		{
			name: "source_dotdot",
			job:  render.TemplateJob{Path: "out.txt", Mode: "0644", Source: "../secret", Data: minimalCLITemplateData()},
		},
	}
	for _, tc := range cases {
		tc := tc
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			sub := testutil.New(t)
			sub.Phase("refuse")
			inv, err := render.RenderTemplate(cat, tc.job, nil)
			sub.Assert("nil_inventory", inv == nil, true, inv == nil)
			if err == nil {
				sub.Fail("expected_error", "want fs.unsafe_path")
			}
			fe := asFoundry(t, err)
			sub.Assert("id", fe.ID() == diagnostic.IDFSUnsafePath,
				diagnostic.IDFSUnsafePath, fe.ID())
			sub.Step("refuse", testutil.OutcomeOK, fmt.Sprintf(
				"path=%s source=%s error_id=%s outcome=refused",
				tc.job.Path, tc.job.Source, fe.ID(),
			))
			sub.PhaseEnd("refuse", testutil.OutcomeOK)
		})
	}
	log.PhaseEnd("escape", testutil.OutcomeOK)
}

// TestTemplateMissingCatalogSource returns stable catalog.invalid.
func TestTemplateMissingCatalogSource(t *testing.T) {
	log := testutil.New(t)
	log.Phase("missing_source")
	cat := templateFixtureCatalog()
	inv, err := render.RenderTemplate(cat, render.TemplateJob{
		Path:   "out.txt",
		Mode:   "0644",
		Source: "fixtures/does-not-exist.tmpl",
		Data:   minimalCLITemplateData(),
	}, nil)
	log.Assert("nil_inventory", inv == nil, true, inv == nil)
	if err == nil {
		log.Fail("expected_error", "want catalog.invalid")
	}
	fe := asFoundry(t, err)
	log.Assert("id", fe.ID() == diagnostic.IDCatalogInvalid,
		diagnostic.IDCatalogInvalid, fe.ID())
	log.Step("missing", testutil.OutcomeOK, fmt.Sprintf(
		"template_id=fixtures/does-not-exist.tmpl error_id=%s outcome=fail",
		fe.ID(),
	))
	log.PhaseEnd("missing_source", testutil.OutcomeOK)
}

// TestTemplateDuplicateJobPath fails closed on duplicate destinations.
func TestTemplateDuplicateJobPath(t *testing.T) {
	log := testutil.New(t)
	log.Phase("dup_path")
	cat := templateFixtureCatalog()
	data := minimalCLITemplateData()
	_, err := render.RenderTemplateAll(cat, []render.TemplateJob{
		{Path: "out.txt", Mode: "0644", Source: "fixtures/simple.tmpl", Data: data},
		{Path: "out.txt", Mode: "0644", Source: "fixtures/simple.tmpl", Data: data},
	}, nil)
	if err == nil {
		log.Fail("expected_error", "want render.failed on duplicate path")
	}
	fe := asFoundry(t, err)
	log.Assert("id", fe.ID() == diagnostic.IDRenderFailed,
		diagnostic.IDRenderFailed, fe.ID())
	log.Step("dup", testutil.OutcomeOK, fmt.Sprintf(
		"path=out.txt error_id=%s outcome=fail", fe.ID(),
	))
	log.PhaseEnd("dup_path", testutil.OutcomeOK)
}

// TestTemplateEmbeddedTUIMain renders the real catalog TUI main stub.
func TestTemplateEmbeddedTUIMain(t *testing.T) {
	log := testutil.New(t)
	log.Phase("embedded_tui")
	cat := mustLoadCatalog(t)
	data := render.TemplateData{
		Name:        "minimal-tui",
		Binary:      "minimal-tui",
		Module:      "github.com/example/minimal-tui",
		Description: "Minimal TUI",
		Archetype:   "tui",
		Visibility:  "private",
	}
	src := "archetypes/tui/files/main.go.tmpl"
	inv, err := render.RenderTemplate(cat, render.TemplateJob{
		Path:   "cmd/minimal-tui/main.go",
		Mode:   "0644",
		Source: src,
		Owner:  "archetype:tui",
		Data:   data,
	}, nil)
	if err != nil {
		log.Fail("render", err.Error())
	}
	out, ok := inv.Content("cmd/minimal-tui/main.go")
	log.Assert("present", ok, true, ok)
	log.Assert("binary", bytes.Contains(out, []byte("minimal-tui")),
		true, bytes.Contains(out, []byte("minimal-tui")))
	log.Assert("package", bytes.Contains(out, []byte("package main")),
		true, bytes.Contains(out, []byte("package main")))
	e := inv.Entries()[0]
	log.Step("file", testutil.OutcomeOK, fmt.Sprintf(
		"template_id=%s input_digest=%s output_digest=%s outcome=ok",
		e.Source, e.SourceDigest, e.ContentDigest,
	))
	log.PhaseEnd("embedded_tui", testutil.OutcomeOK)
}
