// Package inventory is the first real domain package for the repo-map dogfood
// project. It does not import Cobra (Section 17.4 / REQ-065 / REQ-067).
//
// Foundry-owned dogfood overlay only — never generated by the CLI archetype.
package inventory

import (
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Entry is one filesystem path relative to the walk root.
type Entry struct {
	Path  string `json:"path"`
	Bytes int64  `json:"bytes"`
	Dir   bool   `json:"dir"`
}

// Options control Walk.
type Options struct {
	// Root is the directory to inventory; empty means ".".
	Root string
	// MaxDepth limits directory depth (0 = unlimited). Root is depth 0.
	MaxDepth int
}

// Walk returns a deterministic inventory of Root (sorted by path).
// Skips ".git" directory trees. Symlinks are reported as entries but not followed.
func Walk(opts Options) ([]Entry, error) {
	root := opts.Root
	if root == "" {
		root = "."
	}
	abs, err := filepath.Abs(root)
	if err != nil {
		return nil, err
	}
	st, err := os.Lstat(abs)
	if err != nil {
		return nil, err
	}
	if !st.IsDir() {
		return nil, fmt.Errorf("not a directory: %s", root)
	}

	var out []Entry
	err = filepath.WalkDir(abs, func(path string, d fs.DirEntry, walkErr error) error {
		if walkErr != nil {
			return walkErr
		}
		rel, err := filepath.Rel(abs, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		// Skip .git entirely (common repository inventory exclusion).
		if d.IsDir() && (d.Name() == ".git" || strings.HasPrefix(rel, ".git"+string(os.PathSeparator))) {
			return fs.SkipDir
		}
		if opts.MaxDepth > 0 {
			depth := strings.Count(rel, string(os.PathSeparator)) + 1
			if d.IsDir() && depth > opts.MaxDepth {
				return fs.SkipDir
			}
			if depth > opts.MaxDepth {
				return nil
			}
		}
		info, err := d.Info()
		if err != nil {
			return err
		}
		// Normalize to slash paths for stable text/JSON across platforms.
		out = append(out, Entry{
			Path:  filepath.ToSlash(rel),
			Bytes: info.Size(),
			Dir:   d.IsDir(),
		})
		return nil
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Path < out[j].Path })
	return out, nil
}

// FormatText writes one relative path per line (dirs end with "/").
func FormatText(entries []Entry) string {
	var b strings.Builder
	for _, e := range entries {
		if e.Dir {
			b.WriteString(e.Path)
			if !strings.HasSuffix(e.Path, "/") {
				b.WriteByte('/')
			}
			b.WriteByte('\n')
			continue
		}
		b.WriteString(e.Path)
		b.WriteByte('\n')
	}
	return b.String()
}

// FormatJSON returns a stable JSON array of Entry values.
func FormatJSON(entries []Entry) (string, error) {
	if entries == nil {
		entries = []Entry{}
	}
	raw, err := json.MarshalIndent(entries, "", "  ")
	if err != nil {
		return "", err
	}
	return string(raw) + "\n", nil
}
